use std::collections::BTreeSet;

use serde::Serialize;
use serde_json::{Map, Value};

use crate::adapter::GeneratedFile;
use crate::error::{message, Result};
use crate::model::{CanonicalModel, Entity, Field};
use crate::normalize::resolve_schema_node;
use crate::utils::to_json_literal;

#[derive(Debug, Clone, Serialize, PartialEq)]
pub struct MapperReport {
    #[serde(rename = "formatVersion")]
    pub format_version: String,
    pub diagnostics: Vec<MapperDiagnostic>,
    pub summary: MapperSummary,
}

#[derive(Debug, Clone, Serialize, PartialEq)]
pub struct MapperSummary {
    #[serde(rename = "totalDiagnostics")]
    pub total_diagnostics: usize,
    pub entities: usize,
}

#[derive(Debug, Clone, Serialize, PartialEq)]
pub struct MapperDiagnostic {
    pub code: String,
    pub direction: String,
    pub entity: String,
    pub schema: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub field: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub property: Option<String>,
    pub message: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct SchemaProperty {
    name: String,
    property_type: String,
}

pub fn build_mapper_report(
    document: &Value,
    canonical_model: &CanonicalModel,
) -> Result<MapperReport> {
    let mut diagnostics = Vec::new();
    for entity in &canonical_model.entities {
        diagnostics.extend(create_mapping_diagnostics(entity, document)?);
        diagnostics.extend(read_mapping_diagnostics(entity, document)?);
    }

    Ok(MapperReport {
        format_version: String::from("0.1"),
        summary: MapperSummary {
            total_diagnostics: diagnostics.len(),
            entities: canonical_model.entities.len(),
        },
        diagnostics,
    })
}

pub fn generate_mapper_files(
    document: &Value,
    canonical_model: &CanonicalModel,
    filename: Option<&str>,
    diagnostics_filename: Option<&str>,
) -> Result<Vec<GeneratedFile>> {
    let mut dto_schema_names = BTreeSet::new();
    for entity in &canonical_model.entities {
        for pointer in [
            entity.source_schemas.create.as_deref(),
            entity.source_schemas.read.as_deref(),
            entity.source_schemas.update.as_deref(),
        ] {
            if let Some(schema_name) = schema_name_from_pointer(pointer) {
                dto_schema_names.insert(schema_name.to_owned());
            }
        }
    }

    let mut sections = vec![String::from(
        "// Generated by OpenModels. DTO interfaces are inferred from OpenAPI schemas.",
    )];

    let record_interfaces = canonical_model
        .entities
        .iter()
        .map(build_record_interface)
        .collect::<Vec<_>>();
    sections.push(record_interfaces.join("\n\n"));

    let mut dto_interfaces = Vec::new();
    for schema_name in dto_schema_names {
        dto_interfaces.push(build_dto_interface(document, &schema_name)?);
    }
    if !dto_interfaces.is_empty() {
        sections.push(dto_interfaces.join("\n\n"));
    }

    let mut mapper_blocks = Vec::new();
    for entity in &canonical_model.entities {
        if let Some(block) = build_create_mapper(entity, document)? {
            mapper_blocks.push(block);
        }
        if let Some(block) = build_update_mapper(entity) {
            mapper_blocks.push(block);
        }
        if let Some(block) = build_read_mapper(entity, document)? {
            mapper_blocks.push(block);
        }
    }
    if !mapper_blocks.is_empty() {
        sections.push(mapper_blocks.join("\n\n"));
    }

    let report = build_mapper_report(document, canonical_model)?;

    Ok(vec![
        GeneratedFile {
            path: filename.unwrap_or("dto-mappers.ts").to_owned(),
            content: format!("{}\n", sections.join("\n\n")),
        },
        GeneratedFile {
            path: diagnostics_filename
                .unwrap_or("dto-mappers.diagnostics.json")
                .to_owned(),
            content: format!("{}\n", serde_json::to_string_pretty(&report)?),
        },
    ])
}

fn schema_name_from_pointer(pointer: Option<&str>) -> Option<&str> {
    let pointer = pointer?;
    pointer
        .strip_prefix("#/components/schemas/")
        .filter(|value| !value.is_empty())
}

fn property_name_from_pointer(pointer: Option<&str>) -> Option<&str> {
    let pointer = pointer?;
    let (_, property_name) = pointer.rsplit_once("/properties/")?;
    Some(property_name)
}

fn storage_type_to_ts(field: &Field) -> String {
    let base = match field.field_type.as_str() {
        "uuid" | "varchar" | "text" => "string",
        "integer" => "number",
        "boolean" => "boolean",
        "timestamp" | "timestamptz" => "Date",
        _ => "unknown",
    };
    if field.nullable {
        format!("{base} | null")
    } else {
        String::from(base)
    }
}

fn ts_type_from_openapi_node(node: &Value) -> String {
    let Some(object) = node.as_object() else {
        return String::from("unknown");
    };
    if let Some(reference) = object.get("$ref").and_then(Value::as_str) {
        return schema_name_from_pointer(Some(reference))
            .map(String::from)
            .unwrap_or_else(|| String::from("unknown"));
    }
    if let Some(values) = object.get("enum").and_then(Value::as_array) {
        return values
            .iter()
            .map(to_json_literal)
            .collect::<Vec<_>>()
            .join(" | ");
    }

    match object.get("type") {
        Some(Value::Array(items)) => {
            let non_null_types = items
                .iter()
                .filter_map(Value::as_str)
                .filter(|item| *item != "null")
                .collect::<Vec<_>>();
            if non_null_types.len() == 1 && items.iter().any(|item| item.as_str() == Some("null")) {
                let mut base_node = object.clone();
                base_node.insert(
                    String::from("type"),
                    Value::String(String::from(non_null_types[0])),
                );
                return format!(
                    "{} | null",
                    ts_type_from_openapi_node(&Value::Object(base_node))
                );
            }
            String::from("unknown")
        }
        Some(Value::String(node_type)) => match node_type.as_str() {
            "string" => String::from("string"),
            "integer" | "number" => String::from("number"),
            "boolean" => String::from("boolean"),
            "array" => {
                let item_type = object
                    .get("items")
                    .map(ts_type_from_openapi_node)
                    .unwrap_or_else(|| String::from("unknown"));
                format!("Array<{item_type}>")
            }
            "object" => String::from("Record<string, unknown>"),
            _ => String::from("unknown"),
        },
        _ => String::from("unknown"),
    }
}

fn schema_properties(
    document: &Value,
    schema_pointer: Option<&str>,
) -> Result<(Vec<SchemaProperty>, BTreeSet<String>)> {
    let Some(schema_pointer) = schema_pointer else {
        return Ok((Vec::new(), BTreeSet::new()));
    };
    let schema_node = resolve_schema_node(document, schema_pointer)?;
    let object = schema_node.as_object().ok_or_else(|| {
        message(format!(
            "Schema '{}' must resolve to an object.",
            schema_pointer
        ))
    })?;
    let properties = object
        .get("properties")
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_else(Map::new);
    let required = object
        .get("required")
        .and_then(Value::as_array)
        .map(|items| {
            items
                .iter()
                .filter_map(Value::as_str)
                .map(String::from)
                .collect::<BTreeSet<_>>()
        })
        .unwrap_or_default();

    let mut items = Vec::new();
    for (property_name, property_node) in properties {
        let resolved = if let Some(reference) = property_node
            .as_object()
            .and_then(|map| map.get("$ref"))
            .and_then(Value::as_str)
        {
            resolve_schema_node(document, reference)?
        } else {
            &property_node
        };
        items.push(SchemaProperty {
            name: property_name,
            property_type: ts_type_from_openapi_node(resolved),
        });
    }
    Ok((items, required))
}

fn build_record_interface(entity: &Entity) -> String {
    let mut lines = vec![format!("export interface {}Record {{", entity.name)];
    for field in &entity.fields {
        if !field.persisted {
            continue;
        }
        lines.push(format!("  {}: {};", field.name, storage_type_to_ts(field)));
    }
    lines.push(String::from("}"));
    lines.join("\n")
}

fn build_dto_interface(document: &Value, schema_name: &str) -> Result<String> {
    let schema_pointer = format!("#/components/schemas/{schema_name}");
    let (properties, required) = schema_properties(document, Some(&schema_pointer))?;
    let mut lines = vec![format!("export interface {schema_name} {{")];
    for property in properties {
        let optional = if required.contains(&property.name) {
            ""
        } else {
            "?"
        };
        lines.push(format!(
            "  {}{}: {};",
            property.name, optional, property.property_type
        ));
    }
    lines.push(String::from("}"));
    Ok(lines.join("\n"))
}

fn create_mapping_diagnostics(entity: &Entity, document: &Value) -> Result<Vec<MapperDiagnostic>> {
    let create_schema_pointer = entity.source_schemas.create.as_deref();
    let Some(create_schema_name) = schema_name_from_pointer(create_schema_pointer) else {
        return Ok(Vec::new());
    };

    let (create_properties, _required) = schema_properties(document, create_schema_pointer)?;
    let mapped_properties = entity
        .fields
        .iter()
        .filter_map(|field| property_name_from_pointer(field.source_schemas.create.as_deref()))
        .collect::<BTreeSet<_>>();

    let mut diagnostics = Vec::new();
    for field in &entity.fields {
        if field.source_schemas.create.is_some() {
            continue;
        }
        if field.persisted
            && field.generated == "none"
            && field.default.is_none()
            && !field.nullable
        {
            diagnostics.push(MapperDiagnostic {
                code: String::from("unmapped-entity-field"),
                direction: String::from("create"),
                entity: entity.name.clone(),
                schema: String::from(create_schema_name),
                field: Some(field.name.clone()),
                property: None,
                message: format!(
                    "Field '{}.{}' has no direct create mapping and requires a transform or manual assignment.",
                    entity.name, field.name
                ),
            });
        }
    }

    for property in create_properties {
        if mapped_properties.contains(property.name.as_str()) {
            continue;
        }
        diagnostics.push(MapperDiagnostic {
            code: String::from("unmapped-dto-property"),
            direction: String::from("create"),
            entity: entity.name.clone(),
            schema: String::from(create_schema_name),
            field: None,
            property: Some(property.name.clone()),
            message: format!(
                "Property '{}.{}' is not mapped to any persistence field.",
                create_schema_name, property.name
            ),
        });
    }

    Ok(diagnostics)
}

fn read_mapping_diagnostics(entity: &Entity, document: &Value) -> Result<Vec<MapperDiagnostic>> {
    let read_schema_pointer = entity.source_schemas.read.as_deref();
    let Some(read_schema_name) = schema_name_from_pointer(read_schema_pointer) else {
        return Ok(Vec::new());
    };

    let (read_properties, _required) = schema_properties(document, read_schema_pointer)?;
    let mapped_properties = entity
        .fields
        .iter()
        .filter_map(|field| property_name_from_pointer(field.source_schemas.read.as_deref()))
        .collect::<BTreeSet<_>>();

    let mut diagnostics = Vec::new();
    for property in read_properties {
        if mapped_properties.contains(property.name.as_str()) {
            continue;
        }
        diagnostics.push(MapperDiagnostic {
            code: String::from("unmapped-dto-property"),
            direction: String::from("read"),
            entity: entity.name.clone(),
            schema: String::from(read_schema_name),
            field: None,
            property: Some(property.name.clone()),
            message: format!(
                "Property '{}.{}' is not mapped from any persistence field.",
                read_schema_name, property.name
            ),
        });
    }

    Ok(diagnostics)
}

fn mapping_function_name(entity_name: &str, direction: &str) -> Result<String> {
    match direction {
        "create" => Ok(format!("map{entity_name}CreateInputTo{entity_name}Record")),
        "update" => Ok(format!(
            "map{entity_name}UpdateInputTo{entity_name}RecordPatch"
        )),
        "read" => Ok(format!("map{entity_name}RecordTo{entity_name}Response")),
        _ => Err(message(format!(
            "Unsupported mapping direction: {direction}"
        ))),
    }
}

fn build_create_mapper(entity: &Entity, document: &Value) -> Result<Option<String>> {
    let schema_pointer = entity.source_schemas.create.as_deref();
    let Some(schema_name) = schema_name_from_pointer(schema_pointer) else {
        return Ok(None);
    };

    let mut assignments = Vec::new();
    for field in &entity.fields {
        let property_pointer = field.source_schemas.create.as_deref();
        let Some(property_name) = property_name_from_pointer(property_pointer) else {
            continue;
        };
        let mut expression = format!("input.{property_name}");
        if matches!(field.field_type.as_str(), "timestamp" | "timestamptz") {
            let property_node = resolve_schema_node(
                document,
                property_pointer.expect("property pointer should exist"),
            )?;
            if property_node.get("type").and_then(Value::as_str) == Some("string") {
                expression = format!("new Date(input.{property_name})");
            }
        }
        assignments.push(format!("    {}: {},", field.name, expression));
    }

    let todo_comments = create_mapping_diagnostics(entity, document)?
        .into_iter()
        .filter(|diagnostic| diagnostic.code == "unmapped-entity-field")
        .map(|diagnostic| diagnostic.message)
        .collect::<Vec<_>>();

    let mut lines = vec![format!(
        "export function {}(input: {}): Partial<{}Record> {{",
        mapping_function_name(&entity.name, "create")?,
        schema_name,
        entity.name
    )];
    for comment in todo_comments {
        lines.push(format!("  // TODO(openmodels): {comment}"));
    }
    lines.push(String::from("  return {"));
    lines.extend(assignments);
    lines.push(String::from("  };"));
    lines.push(String::from("}"));
    Ok(Some(lines.join("\n")))
}

fn build_update_mapper(entity: &Entity) -> Option<String> {
    let schema_name = schema_name_from_pointer(entity.source_schemas.update.as_deref())?;

    let mut assignments = Vec::new();
    for field in &entity.fields {
        let property_name = property_name_from_pointer(field.source_schemas.update.as_deref());
        let Some(property_name) = property_name else {
            continue;
        };
        assignments.push(format!(
            "    ...(input.{property_name} !== undefined ? {{ {}: input.{property_name} }} : {{}}),",
            field.name
        ));
    }

    let mut lines = vec![format!(
        "export function {}(input: {}): Partial<{}Record> {{",
        mapping_function_name(&entity.name, "update").expect("update direction"),
        schema_name,
        entity.name
    )];
    lines.push(String::from("  return {"));
    lines.extend(assignments);
    lines.push(String::from("  };"));
    lines.push(String::from("}"));
    Some(lines.join("\n"))
}

fn build_read_mapper(entity: &Entity, document: &Value) -> Result<Option<String>> {
    let schema_pointer = entity.source_schemas.read.as_deref();
    let Some(schema_name) = schema_name_from_pointer(schema_pointer) else {
        return Ok(None);
    };

    let mut assignments = Vec::new();
    for field in &entity.fields {
        let property_pointer = field.source_schemas.read.as_deref();
        let Some(property_name) = property_name_from_pointer(property_pointer) else {
            continue;
        };
        let mut expression = format!("record.{}", field.name);
        if matches!(field.field_type.as_str(), "timestamp" | "timestamptz") {
            let property_node = resolve_schema_node(
                document,
                property_pointer.expect("property pointer should exist"),
            )?;
            if property_node.get("type").and_then(Value::as_str) == Some("string") {
                if field.nullable {
                    expression = format!(
                        "record.{} ? record.{}.toISOString() : null",
                        field.name, field.name
                    );
                } else {
                    expression = format!("record.{}.toISOString()", field.name);
                }
            }
        }
        assignments.push(format!("    {property_name}: {expression},"));
    }

    let mut lines = vec![format!(
        "export function {}(record: {}Record): Partial<{}> {{",
        mapping_function_name(&entity.name, "read")?,
        entity.name,
        schema_name
    )];
    lines.push(String::from("  return {"));
    lines.extend(assignments);
    lines.push(String::from("  };"));
    lines.push(String::from("}"));
    Ok(Some(lines.join("\n")))
}
